# : Manager [[[

[manager]
cwd = { fg = "#e3e1ed" }

# Tab
tab_active = { fg = "#001b96", bg = "#bbc3ff", bold = true }
tab_inactive = { fg = "#dfe0ff", bg = "#000e5f" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff866c", bg = "#ff866c" }
marker_cut = { fg = "#ffdad2", bg = "#ffdad2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffb4a3", bg = "#ffb4a3" }

# Count
count_copied = { fg = "#3d0700", bg = "#ffdad2" }
count_cut = { fg = "#3d0700", bg = "#ffdad2" }
count_selected = { fg = "#001b96", bg = "#ffb4a3" }

# Border
border_symbol = "│"
border_style  = { fg = "#bbc3ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#001b96", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bbc3ff", fg = "#001b96", bold = true }
normal_alt  = { bg = "#444654", fg = "#c5c5d7" }

# Select mode
select_main = { bg = "#bbc3ff", fg = "#242c5e", bold = true }
select_alt  = { bg = "#444654", fg = "#c5c5d7" }

# Unset mode
unset_main = { bg = "#ffb4a3", fg = "#621100", bold = true }
unset_alt  = { bg = "#444654", fg = "#c5c5d7" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bbc3ff", bg = "#383841" }
progress_error = { fg = "#ffb4ab", bg = "#383841" }

# Permissions
permissions_t = { fg = "#223cff" }
permissions_w = { fg = "#ff370a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff5c39" }
permissions_s = { fg = "#464cff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bbc3ff" }
active = { fg = "#ffb4a3", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#bbc3ff" }
value = { fg = "#e3e1ed" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bbc3ff", bg = "#001b96" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#bbc3ff" }
title = {}
hovered = { fg = "#ffdad2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#383841" }
cand = { fg = "#bbc3ff" }
rest = { fg = "#001b96" }
desc = { fg = "#e3e1ed" }
separator = " ▶ "
separator_style = { fg = "#e3e1ed" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e3e1ed" }
run = { fg = "#e3e1ed" }
footer = { fg = "#242c5e", bg = "#bbc3ff" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#ffb4a3" }
title_warn = { fg = "#bbc3ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e3e1ed" },
    { name = "*/", fg = "#bbc3ff" },
]

# : ]]]