# : Manager [[[

[manager]
cwd = { fg = "#e5e1e5" }

# Tab
tab_active = { fg = "#292e4f", bg = "#c0c4ee", bold = true }
tab_inactive = { fg = "#dfe0ff", bg = "#141939" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff71cd", bg = "#ff71cd" }
marker_cut = { fg = "#ffd7f1", bg = "#ffd7f1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e8b9d9", bg = "#e8b9d9" }

# Count
count_copied = { fg = "#2e1129", bg = "#ffd7f1" }
count_cut = { fg = "#2e1129", bg = "#ffd7f1" }
count_selected = { fg = "#292e4f", bg = "#e8b9d9" }

# Border
border_symbol = "│"
border_style  = { fg = "#c0c4ee" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#292e4f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c0c4ee", fg = "#292e4f", bold = true }
normal_alt  = { bg = "#46464e", fg = "#c7c5cf" }

# Select mode
select_main = { bg = "#c5c5d7", fg = "#2e2f3e", bold = true }
select_alt  = { bg = "#46464e", fg = "#c7c5cf" }

# Unset mode
unset_main = { bg = "#e8b9d9", fg = "#46253f", bold = true }
unset_alt  = { bg = "#46464e", fg = "#c7c5cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c0c4ee", bg = "#39393c" }
progress_error = { fg = "#ffb4ab", bg = "#39393c" }

# Permissions
permissions_t = { fg = "#6a6a99" }
permissions_w = { fg = "#c2469a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3ebb" }
permissions_s = { fg = "#464cff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c0c4ee" }
active = { fg = "#e8b9d9", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c0c4ee" }
value = { fg = "#e5e1e5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c0c4ee", bg = "#292e4f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c0c4ee" }
title = {}
hovered = { fg = "#ffd7f1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393c" }
cand = { fg = "#c0c4ee" }
rest = { fg = "#292e4f" }
desc = { fg = "#e5e1e5" }
separator = " ▶ "
separator_style = { fg = "#e5e1e5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e5e1e5" }
run = { fg = "#e5e1e5" }
footer = { fg = "#2e2f3e", bg = "#c5c5d7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e8b9d9" }
title_warn = { fg = "#c0c4ee" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e5e1e5" },
    { name = "*/", fg = "#c0c4ee" },
]

# : ]]]