# : Manager [[[

[manager]
cwd = { fg = "#e9e1dc" }

# Tab
tab_active = { fg = "#422c11", bg = "#e4c09a", bold = true }
tab_inactive = { fg = "#ffddb9", bg = "#2a1701" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6fb1f6", bg = "#6fb1f6" }
marker_cut = { fg = "#cfe5fc", bg = "#cfe5fc" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b3c9df", bg = "#b3c9df" }

# Count
count_copied = { fg = "#061d2e", bg = "#cfe5fc" }
count_cut = { fg = "#061d2e", bg = "#cfe5fc" }
count_selected = { fg = "#422c11", bg = "#b3c9df" }

# Border
border_symbol = "│"
border_style  = { fg = "#e4c09a" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#422c11", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e4c09a", fg = "#422c11", bold = true }
normal_alt  = { bg = "#4e453c", fg = "#d2c4b8" }

# Select mode
select_main = { bg = "#d7c3b1", fg = "#3a2e21", bold = true }
select_alt  = { bg = "#4e453c", fg = "#d2c4b8" }

# Unset mode
unset_main = { bg = "#b3c9df", fg = "#1d3244", bold = true }
unset_alt  = { bg = "#4e453c", fg = "#d2c4b8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e4c09a", bg = "#3c3835" }
progress_error = { fg = "#ffb4ab", bg = "#3c3835" }

# Permissions
permissions_t = { fg = "#9e7551" }
permissions_w = { fg = "#4a7caf" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3f97f3" }
permissions_s = { fg = "#ff9320" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e4c09a" }
active = { fg = "#b3c9df", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#e4c09a" }
value = { fg = "#e9e1dc" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e4c09a", bg = "#422c11" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e4c09a" }
title = {}
hovered = { fg = "#cfe5fc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c3835" }
cand = { fg = "#e4c09a" }
rest = { fg = "#422c11" }
desc = { fg = "#e9e1dc" }
separator = " ▶ "
separator_style = { fg = "#e9e1dc" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e9e1dc" }
run = { fg = "#e9e1dc" }
footer = { fg = "#3a2e21", bg = "#d7c3b1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b3c9df" }
title_warn = { fg = "#e4c09a" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e9e1dc" },
    { name = "*/", fg = "#e4c09a" },
]

# : ]]]