# : Manager [[[

[manager]
cwd = { fg = "#e5e1e3" }

# Tab
tab_active = { fg = "#2d2f44", bg = "#c3c4df", bold = true }
tab_inactive = { fg = "#e0e0fc", bg = "#181a2e" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#e6bc5f", bg = "#e6bc5f" }
marker_cut = { fg = "#f4e1b7", bg = "#f4e1b7" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d7c59d", bg = "#d7c59d" }

# Count
count_copied = { fg = "#241a02", bg = "#f4e1b7" }
count_cut = { fg = "#241a02", bg = "#f4e1b7" }
count_selected = { fg = "#2d2f44", bg = "#d7c59d" }

# Border
border_symbol = "│"
border_style  = { fg = "#c3c4df" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#2d2f44", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c3c4df", fg = "#2d2f44", bold = true }
normal_alt  = { bg = "#46464d", fg = "#c7c5cd" }

# Select mode
select_main = { bg = "#c7c5d1", fg = "#2f3039", bold = true }
select_alt  = { bg = "#46464d", fg = "#c7c5cd" }

# Unset mode
unset_main = { bg = "#d7c59d", fg = "#3a2f13", bold = true }
unset_alt  = { bg = "#46464d", fg = "#c7c5cd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c3c4df", bg = "#3a393b" }
progress_error = { fg = "#ffb4ab", bg = "#3a393b" }

# Permissions
permissions_t = { fg = "#75708d" }
permissions_w = { fg = "#9c7f3f" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#e0aa32" }
permissions_s = { fg = "#5454ef" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c3c4df" }
active = { fg = "#d7c59d", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c3c4df" }
value = { fg = "#e5e1e3" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c3c4df", bg = "#2d2f44" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#c3c4df" }
title = {}
hovered = { fg = "#f4e1b7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a393b" }
cand = { fg = "#c3c4df" }
rest = { fg = "#2d2f44" }
desc = { fg = "#e5e1e3" }
separator = " ▶ "
separator_style = { fg = "#e5e1e3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e5e1e3" }
run = { fg = "#e5e1e3" }
footer = { fg = "#2f3039", bg = "#c7c5d1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d7c59d" }
title_warn = { fg = "#c3c4df" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e5e1e3" },
    { name = "*/", fg = "#c3c4df" },
]

# : ]]]